# config.yaml.example

# --- Application Core Settings ---
app_name: "My Awesome Web App"
package_name: "com.yourcompany.awesomeapp"
url: "https://www.example.com/mobile" # Or "file:///android_asset/index.html" for local assets

# --- Android Build Configuration ---
build:
  min_sdk_version: 21         # Minimum Android API level supported
  compile_sdk_version: 34     # Android API level to compile against
  target_sdk_version: 34      # Android API level your app is designed for
  build_tools_version: "34.0.0" # Version of Android build tools (e.g., "34.0.0")
  version_code: 1             # Internal version number for the app (integer)
  version_name: "1.0.0"       # User-visible version name (string)
  
  # --- NEW: Custom Gradle Build Configurations ---
  # These properties will be injected directly into the defaultConfig block
  # of the app/build.gradle file. Useful for buildConfigField, resValue,
  # or other arbitrary defaultConfig properties.
  gradle_custom_configs:
    myNewBuildFlag: true
    apiEndpointUrl: "https://api.example.com"
    featureToggleEnabled: false
    # Example for buildConfigField (string literal needs quotes in YAML and Groovy)
    # myStringField: '"some_quoted_string_value"'
    # Example for resValue (string literal needs quotes in YAML and Groovy)
    # myResValue: '"#FF0000"'

# --- WebView and App Behavior Settings ---
webapp:
  enable_javascript: true
  allow_file_access: false
  orientation: "portrait"
  fullscreen: true
  theme_color: "#2196F3"
  user_agent: ""
  # REMOVE OR COMMENT OUT THESE LINES
  # dom_storage_enabled: true
  # database_enabled: true
  # app_cache_enabled: true
  built_in_zoom_controls: false
  support_zoom: false
# --- App Launcher Icon Settings ---
logo: "my_logo.png"

# --- Splash Screen Settings ---
splash:
  type: "image"
  content: "my_splash.png"
  duration: 3000
  background_color: "#FFFFFF"
  text_color: "#000000"